/* Real PostgreSQL authorization + revision protocol, synthetic auth identities. */
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{randomUUID}=require('crypto');
(async()=>{
  const db=new PGlite();let checks=0;
  const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
  const eq=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;console.log('PASS '+label);};
  const denied=async(fn,label)=>{await assert.rejects(fn);checks++;console.log('PASS '+label);};
  const as=async n=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[n?id(n):'']);await db.exec('set role '+(n?'authenticated':'anon'));};
  const rpc=async(name,args=[])=>{const r=await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) as result`,args);return r.rows[0].result;};
  const read=(kind,target)=>rpc('stocked_kitchen_read',[kind,target]);
  const write=(kind,target,store,key,body,base=0,deleted=false,op=randomUUID())=>rpc('stocked_kitchen_write',[kind,target,store,key,JSON.stringify(body),base,deleted,op]);
  try{
    await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email_confirmed_at timestamptz);
      create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
      grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);
    for(let n=1;n<=5;n++)await db.query('insert into auth.users values($1,$2)',[id(n),n===5?null:new Date().toISOString()]);
    await db.exec(fs.readFileSync(path.join(__dirname,'../supabase/accounts-foundation.sql'),'utf8'));
    const sql=fs.readFileSync(path.join(__dirname,'../supabase/kitchen-sync.sql'),'utf8');await db.exec(sql);await db.exec(sql);checks++;console.log('PASS additive schema reapplies');
    await as(1);const home=await rpc('stocked_create_home',['Test home','Owner']);const invite=await rpc('stocked_create_invite');
    await as(2);await rpc('stocked_join_home',[invite.token,'Member']);
    const privateRow={id:'secret',name:'Private food',qty:2};
    eq((await write('personal',id(2),'items','secret',privateRow)).record.version,1,'member writes own private kitchen');
    await as(1);eq((await db.query('select * from public.stocked_records')).rows.length,0,'household owner cannot list member private records');
    await denied(()=>read('personal',id(2)),'owner cannot read member personal kitchen via RPC');
    await denied(()=>write('personal',id(2),'items','secret',privateRow,1),'owner cannot write member private kitchen');
    const first=await write('household',home.id,'items','milk',{id:'milk',name:'Milk',qty:2});
    eq(first.record.version,1,'shared food created');
    await as(2);eq((await read('household',home.id)).records.length,1,'member reads shared household');
    const op=randomUUID(),next={id:'milk',name:'Milk',qty:1};
    const ack=await write('household',home.id,'items','milk',next,1,false,op);
    eq(ack.record.version,2,'member can edit shared food');
    eq(await write('household',home.id,'items','milk',next,1,false,op),ack,'lost-response retry is idempotent');
    await denied(()=>write('household',home.id,'items','milk',{...next,qty:8},1,false,op),'operation id cannot be reused with different payload');
    await as(1);const stale=await write('household',home.id,'items','milk',{...next,qty:10},1);
    eq(stale.conflict,true,'stale update cannot overwrite newer quantity');eq(stale.record.body.qty,1,'conflict returns current cloud version');
    eq((await write('household',home.id,'items','milk',next,2,true)).record.deleted,true,'deletion is a recoverable tombstone');
    eq((await write('household',home.id,'items','milk',{...next,qty:20},2)).conflict,true,'offline stale edit cannot resurrect deleted food');
    eq((await read('household',home.id)).records[0].body.qty,1,'tombstone preserves previous payload');
    await denied(()=>write('household',home.id,'meta','cfg',{id:'cfg',apiKey:'synthetic'}),'device/provider credentials cannot sync as configuration');
    await denied(()=>write('household',home.id,'recipes','cache',{id:'cache'}),'recipe API cache cannot be uploaded');
    await denied(()=>write('household',home.id,'items','wrong',{id:'another'}),'payload id must match server key');
    await denied(()=>write('household',home.id,'items','big',{id:'big',name:'x'.repeat(524289)}),'oversized record rejected without truncation');
    await denied(()=>db.query("update public.stocked_records set body='{}'"),'direct writes cannot bypass revisions');
    await denied(()=>db.query('select * from public.stocked_operations'),'operation journal is not readable by client');
    await as(3);const other=await rpc('stocked_create_home',['Other home','Other']);
    await denied(()=>read('household',home.id),'another household cannot read first household');
    await denied(()=>write('household',home.id,'saved','recipe',{id:'recipe',name:'Injected'}),'another household cannot write recipes');
    eq((await read('household',other.id)).records.length,0,'new home does not inherit any previous records');
    await as(null);await denied(()=>read('household',home.id),'anonymous cannot read');
    await as(5);await denied(()=>write('personal',id(5),'items','x',{id:'x'}),'unverified account cannot sync');
    await as(1);await rpc('stocked_remove_member',[id(2)]);
    await as(2);await denied(()=>read('household',home.id),'removed member cannot read shared food');
    await denied(()=>write('household',home.id,'items','milk',next,1,false,op),'removed member cannot replay old write');
    eq((await read('personal',id(2))).records[0].body,privateRow,'leaving household preserves private inventory');
    await as(1);await write('personal',id(1),'saved','r',{id:'r',name:'My private recipe'});
    eq((await read('personal',id(1))).records.length,1,'private recipes work without sharing');
    await db.exec('reset role');await db.exec('create table public.sync(id text)');await as(1);
    eq((await rpc('stocked_cloud_status')).ready,false,'legacy project remains gated');
    await denied(()=>read('personal',id(1)),'legacy project cannot start kitchen sync');
    console.log(`ALL ${checks} KITCHEN DATABASE CHECKS PASS`);
  }finally{await db.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
