/* Real app, disposable data. No real kitchen or hosted Auth is touched. */
const http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {execFileSync}=require('child_process');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const ROOT=path.resolve(__dirname,'..'),baseline=execFileSync('git',['show','stocked-v62:index.html'],{cwd:ROOT,encoding:'utf8',maxBuffer:4e6});
let current=false;
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const pathname=new URL(req.url,'http://local').pathname;
  if(pathname==='/'&&!current){res.setHeader('Content-Type','text/html');return res.end(baseline);}
  const file=path.join(ROOT,pathname==='/'?'index.html':pathname);
  if(!file.startsWith(ROOT+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end();}
  res.setHeader('Content-Type',mime[path.extname(file)]||'application/octet-stream');fs.createReadStream(file).pipe(res);
});
(async()=>{let browser;try{
  await new Promise(r=>server.listen(0,'127.0.0.1',r));
  const base=`http://127.0.0.1:${server.address().port}`;
  browser=await chromium.launch({executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe'});
  const ctx=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block',colorScheme:'dark'});
  const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
  await page.goto(base);await page.waitForFunction(()=>typeof S!=='undefined'&&typeof DB!=='undefined');
  await page.evaluate(async()=>{
    welcomed=true;document.getElementById('welcomeOverlay')?.remove();
    S.household={id:'household',locations:[{id:'fridge',name:'Fridge',kind:'fridge'},{id:'pantry',name:'Pantry',kind:'pantry'},{id:'freezer',name:'Freezer',kind:'freezer'}],members:[{name:'Alex'}],staples:[],allergies:[],dislikes:[],people:2,stores:[]};
    S.who=S.household.members[0];S.cfg={autoPhotos:false,confirmActions:false,theme:'light'};await saveHousehold();await saveCfg();
    await addItem({name:'Milk',cat:'dairy-milk',loc:'fridge'});
    await addItem({name:'Rice',cat:'dry-pasta-rice',loc:'pantry',qty:2});
    await addItem({name:'Peas',cat:'frozen-veg',loc:'freezer'});
    await addToList('Eggs');
  });
  const snapshot=()=>page.evaluate(async()=>{const out={};for(const s of ['items','catalog','recipes','meta','log','shopping','plan','saved'])out[s]=(await DB.all(s)).sort((a,b)=>String(a.id).localeCompare(String(b.id)));return out;});
  const before=await snapshot();current=true;await page.reload();await page.waitForFunction(()=>typeof kitchenCheck==='function'&&S.household);
  assert.deepEqual(await snapshot(),before);console.log('PASS v62 upgrade preserves all eight stores');
  assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),'light');
  await page.evaluate(()=>{welcomed=true;document.getElementById('welcomeOverlay')?.remove();S.view='cat';render();});
  assert.match(await page.locator('#catlist').innerText(),/IN STOCK/);
  await page.evaluate(async()=>{await recordCatalog({name:'Hidden deleted product',kind:'product'});await forgetCatalog(catalogFind('Hidden deleted product'));await recordCatalog({name:'Saved meal',kind:'meal'});render();});
  assert.equal(await page.locator('#catlist .item').count(),3);console.log('PASS catalog includes receipt/manual stock, excludes meals and forgotten entries');
  await page.evaluate(()=>reviewReceipt([{name:'Milk',cat:'dairy-milk',count:1},{name:'Rice',cat:'dry-pasta-rice',count:1}]));
  assert.match(await page.locator('.receipt-stock').first().innerText(),/Already at home/);
  await page.locator('.rnm').first().fill('Apples');assert.equal(await page.locator('.receipt-stock').first().innerText(),'');
  await page.locator('.rnm').first().fill('Milk');
  // Simulate storage failure after the item write. Retry must repair catalog, not duplicate food.
  await page.evaluate(()=>{window.originalPut=DB.put;window.failCatalogOnce=true;DB.put=async(s,v)=>{if(s==='catalog'&&window.failCatalogOnce){window.failCatalogOnce=false;throw Error('test storage interruption')}return window.originalPut(s,v);};});
  await page.locator('#dlg [data-a=go]').click();await page.waitForFunction(()=>document.getElementById('receipt-status')?.textContent.includes('could not'));
  assert.equal(await page.evaluate(()=>S.items.filter(i=>i.name==='Milk').length),2);
  await page.evaluate(()=>{DB.put=window.originalPut;const b=document.querySelector('#dlg [data-a=go]');b.click();b.click();});
  await page.locator('#dlg [data-a=trust]').click();
  await page.waitForFunction(()=>!document.getElementById('dlg').open);
  assert.equal(await page.evaluate(()=>S.items.filter(i=>i.name==='Milk').length),2);
  assert.equal(await page.evaluate(()=>S.items.filter(i=>i.name==='Rice').length),2);
  assert.equal(await page.evaluate(()=>S.items.filter(i=>i.name==='Rice').at(-1).loc),'pantry');
  console.log('PASS receipt retry and rapid taps cannot duplicate this review; remembered shelf retained');
  await page.evaluate(()=>reviewReceipt([{name:'Paper bag',cat:'household',count:1}]));
  await page.locator('#rlist input[type=checkbox]').uncheck();await page.locator('#dlg [data-a=go]').click();
  assert.match(await page.locator('#receipt-status').innerText(),/Select at least one/);await page.locator('#dlg [data-a=c]').click();
  console.log('PASS empty receipt selection is recoverable');
  await page.evaluate(()=>{S.cfg.confirmActions=true;kitchenCheck();});
  await page.locator('#check-loc').selectOption('freezer');
  await page.getByRole('button',{name:'Gone',exact:true}).click();
  await page.locator('#dlg [data-a=save]').click();await page.locator('#cdlg [data-a=n]').click();
  assert.equal(await page.evaluate(()=>S.items.find(i=>i.name==='Peas').deleted),false);
  await page.locator('#dlg [data-a=save]').click();await page.locator('#cdlg [data-a=y]').click();
  await page.waitForFunction(()=>!document.getElementById('dlg').open);
  const gone=await page.evaluate(()=>S.items.find(i=>i.name==='Peas'));assert.equal(gone.deleted,true);assert.equal(gone.goneAt,undefined);assert.equal(gone.wasted,undefined);
  await page.getByRole('button',{name:'UNDO',exact:true}).click();
  await page.waitForFunction(()=>!S.items.find(i=>i.name==='Peas').deleted);
  assert.equal(await page.evaluate(()=>S.items.find(i=>i.name==='Peas').deleted),false);
  console.log('PASS batch removal confirmation, cancellation and Undo; no false waste/consumption metrics');
  await page.evaluate(()=>{S.cfg.confirmActions=false;kitchenCheck();});
  await page.locator('#check-loc').selectOption('freezer');await page.getByRole('button',{name:'Still here',exact:true}).click();
  const expiry=await page.evaluate(()=>S.items.find(i=>i.name==='Peas').expires);
  await page.locator('#dlg [data-a=save]').click();await page.waitForFunction(()=>!document.getElementById('dlg').open);
  assert.equal(await page.evaluate(()=>S.items.find(i=>i.name==='Peas').expires),expiry);
  assert.ok(await page.evaluate(()=>S.items.find(i=>i.name==='Peas').checkedAt));
  console.log('PASS still-here preserves quantity and expiration');
  await page.evaluate(()=>kitchenCheck());await page.locator('#check-loc').selectOption('freezer');await page.getByRole('button',{name:'Gone',exact:true}).click();
  await page.evaluate(async()=>{const item=S.items.find(i=>i.name==='Peas');await saveItem({...item,qty:6});});
  await page.locator('#dlg [data-a=save]').click();await page.waitForFunction(()=>!document.getElementById('dlg').open);
  assert.equal(await page.evaluate(()=>S.items.find(i=>i.name==='Peas').deleted),false);
  console.log('PASS changed food is not overwritten by a stale kitchen check');
  const dir=process.env.STOCKED_SCREENSHOTS || path.resolve(ROOT,'../../outputs/stocked-v63');fs.mkdirSync(dir,{recursive:true});
  for(const width of [320,390,768,1280]){
    await page.setViewportSize({width,height:844});await page.evaluate(()=>{S.view='pantry';render();kitchenCheck();});
    assert.ok(await page.evaluate(()=>document.querySelector('#dlg').scrollWidth<=document.querySelector('#dlg').clientWidth+1));
    if(width===390)await page.screenshot({path:path.join(dir,'kitchen-check-390.png')});
    await page.locator('#dlg [data-a=cancel]').click();
    if(width===390)await page.screenshot({path:path.join(dir,'inventory-390.png')});
    await page.evaluate(()=>reviewReceipt([{name:'Milk',cat:'dairy-milk',count:1},{name:'Rice',cat:'dry-pasta-rice',count:1},{name:'Apples',cat:'produce-hardy',count:3}]));
    assert.ok(await page.evaluate(()=>document.querySelector('#dlg').scrollWidth<=document.querySelector('#dlg').clientWidth+1));
    if(width===390)await page.screenshot({path:path.join(dir,'receipt-390.png')});
    await page.locator('#dlg [data-a=c]').click();await page.goto(base+'/guide.html');
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
    assert.match(await page.locator('main').innerText(),/Family cloud accounts are not switched on yet/);
    if(width===390)await page.screenshot({path:path.join(dir,'guide-390.png')});
    await page.goto(base);await page.waitForFunction(()=>typeof kitchenCheck==='function'&&S.household);
  }
  assert.deepEqual(errors,[]);console.log('PASS new screens fit 320/390/768/1280px, guide states limitations, no uncaught errors');
}finally{await browser?.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
